spring:
  datasource:
    url: jdbc:mysql://localhost:3306/appbackend
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Ende1976!#
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
      database: mysql
      database-platform: org.hibernate.dialect.MySQLDialect
